### PR TITLE
Avoid solicit for zero-length prefix

### PR DESCRIPTION
**Pull request by themiron**
Some weird servers could be stressed with IA_PD with zero-length IAPREFIX.
Since -P 0 is used for auto, absence of IAPREFIX is logically the same.

### CODE REVIEW

**Comment by sbyx** [comment]
Thanks for the PR. Has this caused any issues with any real-world implementations already?

**Comment by jimdigriz** [comment]
I'll give this patch a whirl at home.  Might be unrelated but when I ask for a PD using `-P 0` I get a "no prefixes available" message from my ISP (IDNet in the UK) at which point *they* then tear down the PPP connection.

This might stop them at least rudely killing the link, which is somewhat confusing.

**Comment by sbyx** [comment]
Ok, that would indeed be a good reason to merge it ;)

**Comment by themiron** [comment]
yes, including zero iaprefix forces that real-world server (dunno what's exactly on the ISP end) to return StatusCode with UnSpecFail reason

**Comment by sbyx** [comment]
Interesting. Sounds like a server issue to me. Nevertheless i guess your patch doesn't  hurt if it works around.

**Comment by themiron** [comment]
Agree, iaprefix with zero prefix-length is ok per RFC, but usually not used, at least with wide-dhcp6 client. So I guess some server implementations could not have it implemented or have in weird - not really tested way.
Thanks

**Pull request merged**
