### PR TITLE
Allow fallback to stateless mode with too quiet servers and some usage cleanup

### PR DESCRIPTION
**Pull request by themiron**

### CODE REVIEW

**Comment by sbyx** [comment]
Thanks, however I'm not fully convinced about that yet, i.e. I'm not sure how to handle conflicting values for O or M from multiple routers and also PD makes it a bit-difficult as well.

If a router wants to delegate a prefix but no addresses (which some ISPs do) they may only set the O-flag and since we only send one request before adding the stateless "server" to the candidates we might miss the PD if the first solicit gets lost.

Besides I consider dnsmasq's behavior broken and I actually reverted that change in OpenWrt: https://dev.openwrt.org/browser/trunk/package/network/services/dnsmasq/patches/200-fix-dhcpv6-solicit-handling.patch
I couldn't reproduce the WIndows 8 behavior described in the reasoning, it actually behaved correctly for me. Also interpreting that into RFC 3315 17.2.1 is a bit farfetched IMO.

**Comment by themiron** [comment]
Yes, I was worrying about multiple routers environment, but at the moment all other ra values, including  mtu, hoplimit, etc are parsed whatever router they came from, so I have not made any improvements here.
As for servers which are delegating a prefix only with o flag set, the behavior can be easily changed by replacing "pd_mode != IA_MODE_FORCE" with "pd_mode == IA_MODE_NONE".
Even with this, it'll be possible to start odhcp6c in stateless mode with -N none without the need to wait advert from non-responding servers.

With no RA-hints, what’s about following:
1.	Start with info-req, if  -N none and without –P/-N. This means pure stateless mode required, and will help to avoid unnecessary solicit messages, possibly without any response.
2.	Count solicit rounds, after 3rd round allow to fallback to stateless, as if advert with no IA_NA/IA_PD was received?

**Comment by sbyx** [comment]
Okay I guess I can live with that if its only done if pd_mode == IA_MODE_NONE.

**Comment by themiron** [comment]
Thanks, please refer newer two patches
first one disable solicitation in pure stateless mode
second one doesn't rely on RA flags, coz it not seems reliable at 100%, but waits for 3 solicitation rounds before fallback into stateless mode in case of absense of adverts

**Comment by themiron** [comment]
p.s have submitted patch to the mail list also to avoid further issues at least with dnsmasq
http://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2015q2/009429.html

**Comment by RMerl** [comment]
For reference, here's the original pull request to my FW that @pinwing did, and which was later on submitted to Simon:

https://github.com/RMerl/asuswrt-merlin/pull/854

**Pull request closed without merging**
